/* SETTINGS */
export const CHANGE_LOCALE = "CHANGE_LOCALE";

/* AUTH */
export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";
export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";
export const LOGOUT_USER = "LOGOUT_USER";
export const FORGOT_PASSWORD = "FORGOT_PASSWORD";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_ERROR = "FORGOT_PASSWORD_ERROR";
export const RESET_PASSWORD = "RESET_PASSWORD";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_ERROR = "RESET_PASSWORD_ERROR";
/* BOARDAPP*/
export const BOARD_GET_LIST = "BOARD_GET_LIST";
export const BOARD_GET_LIST_SUCCESS = "BOARD_GET_LIST_SUCCESS";
export const BOARD_GET_LIST_ERROR = "BOARD_GET_LIST_ERROR";
export const BOARD_GET_LIST_WITH_FILTER = "BOARD_GET_LIST_WITH_FILTER";
export const BOARD_GET_LIST_WITH_ORDER = "BOARD_GET_LIST_WITH_ORDER";
export const BOARD_GET_LIST_SEARCH = "BOARD_GET_LIST_SEARCH";
export const BOARD_ADD_ITEM = "BOARD_ADD_ITEM";
export const BOARD_ADD_ITEM_SUCCESS = "BOARD_ADD_ITEM_SUCCESS";
export const BOARD_ADD_ITEM_ERROR = "BOARD_ADD_ITEM_ERROR";
export const BOARD_EDIT_ITEM = "BOARD_EDIT_ITEM";
export const BOARD_EDIT_ITEM_SUCCESS = "BOARD_EDIT_ITEM_SUCCESS";
export const BOARD_EDIT_ITEM_ERROR = "BOARD_EDIT_ITEM_ERROR";
export const BOARD_SELECTED_ITEMS_CHANGE = "BOARD_SELECTED_ITEMS_CHANGE";
/* IDEAAPP*/
export const BOARD_SET_CURRENTID = "BOARD_SET_CURRENTID";
export const IDEA_GET_LIST = "IDEA_GET_LIST";
export const IDEA_GET_LIST_SUCCESS = "IDEA_GET_LIST_SUCCESS";
export const IDEA_GET_LIST_ERROR = "IDEA_GET_LIST_ERROR";
export const IDEA_GET_LIST_WITH_FILTER = "IDEA_GET_LIST_WITH_FILTER";
export const IDEA_GET_LIST_WITH_ORDER = "IDEA_GET_LIST_WITH_ORDER";
export const IDEA_GET_LIST_SEARCH = "IDEA_GET_LIST_SEARCH";
export const IDEA_ADD_ITEM = "IDEA_ADD_ITEM";
export const IDEA_ADD_ITEM_SUCCESS = "IDEA_ADD_ITEM_SUCCESS";
export const IDEA_ADD_ITEM_ERROR = "IDEA_ADD_ITEM_ERROR";
export const IDEA_EDIT_ITEM = "IDEA_EDIT_ITEM";
export const IDEA_EDIT_ITEM_SUCCESS = "IDEA_EDIT_ITEM_SUCCESS";
export const IDEA_EDIT_ITEM_ERROR = "IDEA_EDIT_ITEM_ERROR";
export const IDEA_SELECTED_ITEMS_CHANGE = "IDEA_SELECTED_ITEMS_CHANGE";
export const IDEA_DELETE = "IDEA_DELETE";
export const IDEA_DELETE_SUCCESS = "IDEA_DELETE_SUCCESS";
export const IDEA_DELETE_ERROR = "IDEA_DELETE_ERROR";
/*VOTE*/
export const VOTE_UP = "VOTE_UP";
export const VOTE_UP_SUCCESS = "VOTE_UP_SUCCESS";
export const VOTE_UP_ERROR = "VOTE_UP_ERROR";
export const VOTE_DOWN = "VOTE_DOWN";
export const VOTE_DOWN_SUCCESS = "VOTE_DOWN_SUCCESS";
export const VOTE_DOWN_ERROR = "VOTE_DOWN_ERROR";
/* MENU */
export const MENU_SET_CLASSNAMES = "MENU_SET_CLASSNAMES";
export const MENU_CONTAINER_ADD_CLASSNAME = "MENU_CONTAINER_ADD_CLASSNAME";
export const MENU_CLICK_MOBILE_MENU = "MENU_CLICK_MOBILE_MENU";
export const MENU_CHANGE_DEFAULT_CLASSES = "MENU_CHANGE_DEFAULT_CLASSES";
export const MENU_CHANGE_HAS_SUB_ITEM_STATUS =
  "MENU_CHANGE_HAS_SUB_ITEM_STATUS";

export * from "./menu/actions";
export * from "./settings/actions";
export * from "./auth/actions";
export * from "./board/actions";
export * from "./idea/actions";
